variables:
  AutoMix: "Automix Software.sln"

before_script:
  - 'call "D:\Programmes\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
  - echo "Restoring NuGet Packages..."
  - 'msbuild /t:restore /p:Platform="Any CPU" "%AutoMix%"'

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo building...
    - 'msbuild /m /nologo /p:Configuration=Debug;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  except:
    - tags
  artifacts:
    paths:
      - Automix UI/bin/Debug
    expire_in: 10 minutes 

deploy:
  stage: deploy
  script:
    - echo deploying...
    - 'msbuild /m /nologo /p:Configuration=Release;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  artifacts:
    paths:
      - Automix UI/bin/Release
    expire_in: 2 weeks
  only:
    - master