variables:
  AutoMix: "Automix Software.sln"
  DataManagementTestsLib: "Automix Data Management Tests\\bin\\Debug\\Automix Data Management Tests.dll"
  DataManagementTestsFile: "TestResults\\data_management_test.xml"
  AITestsLib: "Automix AI Tests\\bin\\Debug\\Automix AI Tests.dll"
  AITestsFile: "TestResults\\ai_test.xml"
  
before_script:
  - 'call "D:\Programmes\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
  - echo "Restoring NuGet Packages..."
  - 'msbuild /t:restore /p:Platform="Any CPU" "%AutoMix%"'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building..."
    - 'msbuild /m /nologo /p:Configuration=Debug;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  except:
    - tags

test:
  stage: test
  script:
    - echo "Testing..."
    - 'mkdir "TestResults"'
    - 'mstest.exe /testcontainer:"%AITestsLib%"'
    - 'mstest.exe /testcontainer:"%DataManagementTestsLib%"'
  dependencies:
    - build
  except:
    - tags

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - 'msbuild /m /nologo /p:Configuration=Release;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  artifacts:
    paths:
      - Automix UI/bin/Release
    expire_in: 2 weeks
  only:
    - master