variables:
  AutoMix: "Automix Software.sln"
  DataManagementTestsLib: "Automix Data Management Tests\\bin\\Debug\\Automix Data Management Tests.dll"
  AITestsLib: "Automix AI Tests\\bin\\Debug\\Automix AI Tests.dll"
  PathToISCC: "D:\\Programmes\\Inno Setup 5\\ISCC.exe"
  PathToVisualVariables: "D:\\Programmes\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
  
before_script:
  - 'call "%PathToVisualVariables%"'
  - echo "Restoring NuGet Packages..."
  - 'msbuild /t:restore /p:Platform="Any CPU" "%AutoMix%"'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building..."
    - 'msbuild /m /nologo /p:Configuration=Debug;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  except:
    - tags
  artifacts:
    paths:
      - Automix UI/bin/Debug
      - Automix Data Management Tests/bin/Debug
      - Automix AI Tests/bin/Debug
    expire_in: 10 minutes 

test:
  stage: test
  script:
    - echo "Testing..."
    - 'vstest.console.exe "%AITestsLib%" "%DataManagementTestsLib%" /Logger:trx'
    - 'call npm init -f'
    - 'call npm install xml2js'
    - 'call npm install fs'
    - echo "Estimating coverage..."
    - 'node coverage.js'
  dependencies:
    - build
  except:
    - tags

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - 'msbuild /m /nologo /p:Configuration=Release;Platform="Any CPU" "%AutoMix%"'
    - '"%PathToISCC%" "Automix Setup\setup.iss"'
  dependencies: []
  artifacts:
    paths:
      - Automix Setup/bin/
    expire_in: 2 weeks
  only:
    - master