variables:
  AutoMix: "Automix Software.sln"
  DataManagementTestsLib: "Automix Data Management Tests\\bin\\Debug\\Automix Data Management Tests.dll"
  DataManagementTestsFile: "TestResults\\data_management_test.xml"

before_script:
  - 'call "D:\Programmes\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
  - echo "Restoring NuGet Packages..."
  - 'msbuild /t:restore /p:Platform="Any CPU" "%AutoMix%"'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo building...
    - 'msbuild /m /nologo /p:Configuration=Debug;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  except:
    - tags
  artifacts:
    paths:
      - Automix UI/bin/Debug
      - Automix Data Management Tests/bin/Debug
    expire_in: 10 minutes 

test:
  stage: test
  script:
    - echo "Testing..."
    - 'mkdir "TestResults"'
    - 'mstest.exe /testcontainer:"%DataManagementTestsLib%" /resultsfile:"%DataManagementTestsFile%"'
  dependencies:
    - build
  except:
    - tags

deploy:
  stage: deploy
  script:
    - echo deploying...
    - 'msbuild /m /nologo /p:Configuration=Release;Platform="Any CPU" "%AutoMix%"'
  dependencies: []
  artifacts:
    paths:
      - Automix UI/bin/Release
    expire_in: 2 weeks
  only:
    - master