variables:
  AutoMix: "Automix Software\\AutoMix Software.sln"
  TestsLib: "Automix Software\\Debug\\AutoMix Tests.dll"
  TestsFile: "Automix Software\\TestResults\\tests.xml"
  ReleaseDir: "Automix Software\\Release\\"
  DebugMode: "Debug|x86"
  ReleaseMode: "Release|x86"

before_script:
  - 'call "D:\Programmes\Visual Studio Enterprise 2015\VC\bin\amd64\vcvars64.bat"'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo building...
    - 'devenv "%AutoMix%" /Build "%DebugMode%"'
  except:
    - tags
  artifacts:
    paths:
      - Automix Software/Debug
    expire_in: 10 minutes


test:
  stage: test
  script:
    - echo testing...
    - 'mkdir "Automix Software\\TestResults"'
    - 'mstest.exe /testcontainer:"%TestsLib%" /resultsfile:"%TestsFile%"'
  except:
    - tags

deploy:
  stage: deploy
  script:
    - echo deploying...
    - 'devenv "%AutoMix%" /Build "%ReleaseMode%"'
    - 'cd "%ReleaseDir%"'
    - 'for %%i in (*.exe *.dll) do attrib -a "%%i" /s'
    - 'del *.* /s /a:a /q'
    - 'attrib +a *.* /s'
    - 'del *Test*'
    - 'cd ..\\..'
  artifacts:
    paths:
      - "%ReleaseDir%"
    expire_in: 5 minutes
  only:
    - feature/test_ci